version: '3'

services:
  nginx:
    hostname: bb-chat
    build: docker/nginx
    restart: unless-stopped
    ports:
      - 8081:80
    depends_on:
      - php
    volumes:
      - ./:/var/www/symfony
      - ./logs/nginx/:/var/log/nginx

  php:
    build: docker/php-fpm
    restart: unless-stopped
    expose:
      - 9000
    volumes:
      - ./:/var/www/symfony
      - ./logs/symfony:/var/www/symfony/var/logs

